# Generated by Django 2.2.10 on 2021-04-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название опроса')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Дата начала опроса')),
                ('end_date', models.DateField(verbose_name='Дата конца опроса')),
                ('description', models.CharField(max_length=500, verbose_name='Описание опроса')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст вопроса')),
                ('attribute', models.CharField(choices=[('text', 'Текст'), ('one', 'Один вариант'), ('many', 'Несколько вариантов')], default='text', max_length=4)),
            ],
        ),
    ]
