# Generated by Django 2.2.10 on 2021-04-07 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0004_answer_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='Answer',
            name='usr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='pools.Person'),
        ),
    ]
