# Generated by Django 2.2.10 on 2021-04-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0006_auto_20210407_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='person_id',
        ),
        migrations.AddField(
            model_name='person',
            name='person_name',
            field=models.CharField(default='Kuku', max_length=30, verbose_name='Ник пользователя'),
        ),
    ]
