# Generated by Django 2.2.10 on 2021-04-07 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0008_auto_20210407_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pools.Answer'),
        ),
    ]
