# Generated by Django 2.2.10 on 2021-04-07 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0009_variant_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='answer',
        ),
    ]
