# Generated by Django 2.2.10 on 2021-04-10 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0012_auto_20210407_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_text',
        ),
        migrations.AlterField(
            model_name='answer',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='pools.Poll', verbose_name='Опрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='usr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='pools.Person', verbose_name='Автор ответа'),
        ),
        migrations.CreateModel(
            name='AnswerVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_variant_text', models.CharField(max_length=500, verbose_name='Вариант ответа')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='pools.Answer', verbose_name='Вопрос')),
            ],
        ),
    ]
