# Generated by Django 2.2.10 on 2021-04-10 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0013_auto_20210410_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500, verbose_name='Текст вопроса')),
                ('attribute', models.CharField(choices=[('text', 'Текст'), ('one', 'Один вариант'), ('many', 'Несколько вариантов')], default='text', max_length=4, verbose_name='Аттрибут')),
            ],
        ),
        migrations.CreateModel(
            name='QVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_variant_text', models.CharField(max_length=500, verbose_name='Вариант ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_variants', to='pools.Question')),
            ],
        ),
        migrations.RemoveField(
            model_name='poll',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='question_text',
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
        migrations.AddField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='pools.Poll', verbose_name='Опрос'),
        ),
    ]
