# Generated by Django 2.2.10 on 2021-04-11 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0014_auto_20210410_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='usr',
        ),
        migrations.RemoveField(
            model_name='answervariant',
            name='answer_variant_text',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pools.Question', verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='answervariant',
            name='answer_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pools.QVariant', verbose_name='Вариант ответа'),
        ),
        migrations.AlterField(
            model_name='answervariant',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_variants', to='pools.Answer', verbose_name='Вопрос'),
        ),
        migrations.CreateModel(
            name='PollResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.Poll', verbose_name='Опрос')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='pools.Person', verbose_name='Автор ответа')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='poll_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='pools.PollResult', verbose_name='Результаты опроса'),
        ),
    ]
