# Generated by Django 2.2.10 on 2021-04-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0015_auto_20210411_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answervariant',
            name='answer_variant',
        ),
        migrations.AddField(
            model_name='answervariant',
            name='answer_variant_text',
            field=models.CharField(default='', max_length=500, verbose_name='Текст варианта ответа'),
            preserve_default=False,
        ),
    ]
