# Generated by Django 2.2.10 on 2021-04-11 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0016_auto_20210411_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollresult',
            name='usr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_results', to='pools.Person', verbose_name='Автор ответа'),
        ),
    ]
